language: ruby
rvm:
  - 2.5.0
script:
  - bundle exec rake assets:precompile
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
install:
  - nvm install v9.11.1
  - bundle install
  - node -v
  - npm i -g yarn
  - yarn
